### ISSUE TITLE
 lite väl liten text på axel-förklaringarna och texten i legend

### ISSUE THREAD

**Issue by eribul** [eribul/HH_antal_blanketter#1]
> Tack!
> 
> Nu tycker jag det stämmer väl. Jag har loggat in på lite olika kliniker och tycker det ser bra ut.
> 
> En sak som jag såg när jag kollade på blankett-rapporten är att det är lite väl liten text på axel-förklaringarna och texten i legend. Kan du göra dessa lite störr?
> 
> Med vänlig hälsning,
> Erik

**Comment by chezha** [comment]
Justerat .js filer för större font-storlek hos legend och axel-titlar.

**Comment by eribul** [comment]
Ah, Gôtt!
